server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #以ip进行注册
    instance-id: system-service:9001 #注册的服务的实例的标识

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///hrm-system?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
      name: SYSTEM-SERVICE