server:
  port: 1299

zuul:
  routes:
    system:     # 路由名称
      path: /system/**       # 路由匹配的路径
      serviceId: system-service       # 路径匹配的服务名称
  ignored-services: '*'
  prefix: /services

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #以ip进行注册
    instance-id: zuul-server:1299 #注册的服务的实例的标识

spring:
  application:
    name: ZUUL-SERVER